# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ordered_set}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Balthrop"]
  s.date = %q{2011-06-02}
  s.description = %q{Like Set except it maintains the order of objects}
  s.email = %q{code@justinbalthrop.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ordered_set.rb",
    "ordered_set.gemspec",
    "test/ordered_set_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/ninjudd/ordered_set}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Like Set except it maintains the order of objects}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<deep_clonable>, [">= 1.1.0"])
    else
      s.add_dependency(%q<deep_clonable>, [">= 1.1.0"])
    end
  else
    s.add_dependency(%q<deep_clonable>, [">= 1.1.0"])
  end
end

